config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "users#index"
  get "/signup" => "users#signup"
  post "/newuser"  => "users#create"
  get "/login" => "sessions#login"
  get "/create_session" => "sessions#create_session"
  delete "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def current_user 
  	return session[:user]
  end

  def authorize 
  	if current_user == nil
  	  	redirect_to root_path
  	end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create_session
		
		@user = User.find_by(username: params[:username] )
		
		if @user && @user.authenticate(params[:password])
			log_in @user
			redirect_to root_path
			
		else
			puts "Wrong credentials! Enter Again "
			render 'signup'
		end	
	end

	def login

	end


	def destroy
		log_out
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def signup
		@user = User.new
	end

	def create
		@user = User.new(user_params)
	    if(@user.save)
	  		session[:user] = @user
		    redirect_to root_path
	  	else
	  		redirect_to signup_path
		end
	end


	def user_params
    	params.require(:user).permit(:username, :firstname, :lastname, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user] = user
	end

	def log_out
		session.delete(:user)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def logged_in?
		if session[:user] == nil
			return false
		else
			return true
		end
	end

	def current_user 
  		return session[:user]
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QAEngine</title>
  <%= csrf_meta_tags %>

  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/users/index.html.erb
<% if logged_in? %>
	<%= link_to "Logout", logout_path, method: :delete %>
<% else %>
	<%= link_to "Signup", signup_path %>
	<%= link_to "Login", login_path %>
<% end %>

<% if @users %>
	<% @users.each do |u| %>
		<p><%= u.firstname%></p>
		<p><%= u.lastname%></p>
		<p><%= u.username%></p>
		<p><%= u.email%></p>
		<p><%= u.password_digest%></p>
	<% end %>
<% end %>

app/views/users/signup.html.erb
<% link_to "Home", root_path %>

<h2>Sign Up</h2>
<%= form_for(@user, url: {action: :create, controller: :users}, method: :post) do |f| %>
	<%= f.label "First Name : " %>
	<%= f.text_field :firstname %>
	<br>
	<%= f.label "First Name : " %>
	<%= f.text_field :lastname %>
	<br>
	<%= f.label "Email : " %>
	<%= f.text_field :email %>
	<br>
	<%= f.label "Username" %>
	<%= f.text_field :username %>
	<br>
	<%= f.label "password" %>
	<%= f.password_field :password %>
	<br>
	<%= f.label "confirm password" %>
	<%= f.password_field :password_confirmation %>
	<br>
	<%= f.submit "Signup Now"%>
<% end %>